### ISSUE TITLE
About Analysis of Attention Mechanism in paper

### ISSUE THREAD

**Issue by Eurus-Holmes** [soujanyaporia/contextual-fusion#1]
Hi~
In the paper [Contextual Inter-modal Attention for Multi-modal Sentiment Analysis](http://www.aclweb.org/anthology/D18-1382)
the PR curve is not very clear...
<img width="849" alt="2019-02-09 2 37 42" src="https://user-images.githubusercontent.com/34226570/52517594-77da3e80-2c78-11e9-9903-6a8d8c1600d2.png">

And...
I want to know how to get these Figures:
<img width="1233" alt="2019-02-09 2 32 41" src="https://user-images.githubusercontent.com/34226570/52517527-94c24200-2c77-11e9-9bd6-3ae434ec688f.png">

**Comment by deepanwayx** [comment]
Hi @Eurus-Holmes  the precision, recall, f1 values are as follows:

Precision: AV - 63.49, TA - 79.69, VT - 80.31, AVT - 81.28 
Recall: AV - 60.91, TA - 78.93, VT - 80.67, AVT - 80.97 
F1 Score: AV - 60.24, TA - 79.27, VT - 80.48, AVT - 81.12

We used seaborn to create the figures. Here is a minimal example:

`import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(font_scale = 2)

y1 = np.random.random((9,9))
y2 = np.random.random((9,9))

y = np.c_[y1, y2]
        
plt.subplots(figsize=(18, 6))
fig = sns.heatmap(y, linewidths=0, cmap='Blues',
                  yticklabels= ['$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$'],
                  xticklabels= ['$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$', 
                                '$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$'])
        
fig.axvline(x=9, linewidth=10, color='k')
figure = fig.get_figure()
figure.savefig('heatmap.pdf', dpi=2000, bbox_inches='tight')`

**Comment by deepanwayx** [comment]
The precision, recall, f1 values are as follows
Precision: AV - 63.49, TA - 79.69, VT - 80.31, AVT - 81.28 
Recall: AV - 60.91, TA - 78.93, VT - 80.67, AVT - 80.97 
F1 Score: AV - 60.24, TA - 79.27, VT - 80.48, AVT - 81.12

We created the figures using seaborn, here is a minimal example:
```
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(font_scale = 2)

y1 = np.random.random((9,9))
y2 = np.random.random((9,9))

y = np.c_[y1, y2]
        
plt.subplots(figsize=(18, 6))
fig = sns.heatmap(y, linewidths=0, cmap='Blues',
                  yticklabels= ['$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$'],
                  xticklabels= ['$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$', 
                                '$u_1$', '$u_2$', '$u_3$', '$u_4$', '$u_5$', '$u_6$', '$u_7$', '$u_8$', '$u_9$'])
        
fig.axvline(x=9, linewidth=10, color='k')
figure = fig.get_figure()
figure.savefig('heatmap.pdf', dpi=2000, bbox_inches='tight')
```

**Comment by Eurus-Holmes** [comment]
@deepanwayx Got it, thanks for your reply very much!
